; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:WirelessStickV3-ESP32S3]
;; ESP32-S3 development board, with 8MB FLASH and >= 8MB PSRAM (memory_type: qio_opi)
;;board = esp32-s3-devkitc-1 ;; generic dev board; the next line adds PSRAM support
platform = espressif32
board = esp32-s3-devkitc-1
;;board_build.arduino.memory_type = qio_opi     ;; use with PSRAM: 8MB or 16MB
;;board_build.f_flash = 80000000L
;;board_build.flash_mode = qio

framework = arduino
;;monitor_speed = 921600
;;monitor_filters = esp32_exception_decoder
;;upload_protocol = esptool
;;upload_speed = 921600

build_flags = 
  -D ESP32
  -D ARDUINO_ARCH_ESP32
  -D ARDUINO_ARCH_ESP32S3
  -D CONFIG_IDF_TARGET_ESP32S3=1
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_DFU_ON_BOOT=0
  -D CO

  ;; ---RaceLink Device Type---
  -D DEV_TYPE=1 ;; device type number (1 = RaceLink_Gateway_v4, see RaceLinkProto::RL_Dev_Type*)
  -D DEV_TYPE_STR=\"RaceLink_Gateway_v4\"

  ;; Heltec Wireless Stick V3 Pin Definitions
  -D PIN_VEXT=36
  ; --- Radio (SX1262) Pins: bitte an dein Board anpassen ---
  -D RACELINK_SX1262
  -D RACELINK_CS=8
  -D RACELINK_SCK=9
  -D RACELINK_MOSI=10
  -D RACELINK_MISO=11
  -D RACELINK_RST=12
  -D RACELINK_BUSY=13
  -D RACELINK_DIO1=14

  ; --- I2C OLED Pins (SSD1306 64x32) ---
  -D OLED_SDA=17
  -D OLED_SCL=18
  -D OLED_RST=21
  ; Option: erneutes StartReceive nach jedem Paket (siehe Code)
  -D RX_STICKY=1

lib_deps = jgromes/RadioLib @ ^7.4.0
    olikraus/U8g2 @ ^2.36.14
